dist: trusty
sudo: required
language: go
go:
    - 1.9.x

install:
    - ( mkdir -p $GOPATH/src/github.com/containerd && cd $GOPATH/src/github.com/containerd && git clone https://github.com/containerd/containerd.git && cd containerd && git checkout v1.0.0-beta.1 )
    - go get -t ./...

script:
    - go test -race -covermode=atomic -c
    - sudo ./aufs.test -test.root -test.v -test.coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
